// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: proto/agent.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type HealthStatus int32

const (
	HealthStatus_HEALTH_STATUS_UNSPECIFIED HealthStatus = 0
	HealthStatus_HEALTH_STATUS_HEALTHY     HealthStatus = 1
	HealthStatus_HEALTH_STATUS_DEGRADED    HealthStatus = 2
	HealthStatus_HEALTH_STATUS_UNHEALTHY   HealthStatus = 3
)

// Enum value maps for HealthStatus.
var (
	HealthStatus_name = map[int32]string{
		0: "HEALTH_STATUS_UNSPECIFIED",
		1: "HEALTH_STATUS_HEALTHY",
		2: "HEALTH_STATUS_DEGRADED",
		3: "HEALTH_STATUS_UNHEALTHY",
	}
	HealthStatus_value = map[string]int32{
		"HEALTH_STATUS_UNSPECIFIED": 0,
		"HEALTH_STATUS_HEALTHY":     1,
		"HEALTH_STATUS_DEGRADED":    2,
		"HEALTH_STATUS_UNHEALTHY":   3,
	}
)

func (x HealthStatus) Enum() *HealthStatus {
	p := new(HealthStatus)
	*p = x
	return p
}

func (x HealthStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (HealthStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_agent_proto_enumTypes[0].Descriptor()
}

func (HealthStatus) Type() protoreflect.EnumType {
	return &file_proto_agent_proto_enumTypes[0]
}

func (x HealthStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use HealthStatus.Descriptor instead.
func (HealthStatus) EnumDescriptor() ([]byte, []int) {
	return file_proto_agent_proto_rawDescGZIP(), []int{0}
}

type HeartbeatRequest struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	AgentId   string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	Timestamp *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Status    HealthStatus           `protobuf:"varint,3,opt,name=status,proto3,enum=axiom.agent.v1.HealthStatus" json:"status,omitempty"`
	// The current state of the node (Postgres version, running services, etc.)
	// Represented as a Struct to allow for flexible, evolution-friendly reporting.
	CurrentState *structpb.Struct `protobuf:"bytes,4,opt,name=current_state,json=currentState,proto3" json:"current_state,omitempty"`
	// Results of commands that were executed since the last heartbeat.
	Results       []*CommandResult `protobuf:"bytes,5,rep,name=results,proto3" json:"results,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatRequest) Reset() {
	*x = HeartbeatRequest{}
	mi := &file_proto_agent_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatRequest) ProtoMessage() {}

func (x *HeartbeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatRequest.ProtoReflect.Descriptor instead.
func (*HeartbeatRequest) Descriptor() ([]byte, []int) {
	return file_proto_agent_proto_rawDescGZIP(), []int{0}
}

func (x *HeartbeatRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *HeartbeatRequest) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *HeartbeatRequest) GetStatus() HealthStatus {
	if x != nil {
		return x.Status
	}
	return HealthStatus_HEALTH_STATUS_UNSPECIFIED
}

func (x *HeartbeatRequest) GetCurrentState() *structpb.Struct {
	if x != nil {
		return x.CurrentState
	}
	return nil
}

func (x *HeartbeatRequest) GetResults() []*CommandResult {
	if x != nil {
		return x.Results
	}
	return nil
}

type CommandRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Unique identifier for tracking the command.
	CommandId string `protobuf:"bytes,1,opt,name=command_id,json=commandId,proto3" json:"command_id,omitempty"`
	// Types that are valid to be assigned to Command:
	//
	//	*CommandRequest_Reconcile
	//	*CommandRequest_Backup
	//	*CommandRequest_Restart
	//	*CommandRequest_Branch
	//	*CommandRequest_Restore
	//	*CommandRequest_Migration
	//	*CommandRequest_ValidateIndex
	//	*CommandRequest_PromoteToPrimary
	//	*CommandRequest_DrDrill
	Command       isCommandRequest_Command `protobuf_oneof:"command"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommandRequest) Reset() {
	*x = CommandRequest{}
	mi := &file_proto_agent_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommandRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommandRequest) ProtoMessage() {}

func (x *CommandRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommandRequest.ProtoReflect.Descriptor instead.
func (*CommandRequest) Descriptor() ([]byte, []int) {
	return file_proto_agent_proto_rawDescGZIP(), []int{1}
}

func (x *CommandRequest) GetCommandId() string {
	if x != nil {
		return x.CommandId
	}
	return ""
}

func (x *CommandRequest) GetCommand() isCommandRequest_Command {
	if x != nil {
		return x.Command
	}
	return nil
}

func (x *CommandRequest) GetReconcile() *ReconcileCommand {
	if x != nil {
		if x, ok := x.Command.(*CommandRequest_Reconcile); ok {
			return x.Reconcile
		}
	}
	return nil
}

func (x *CommandRequest) GetBackup() *BackupCommand {
	if x != nil {
		if x, ok := x.Command.(*CommandRequest_Backup); ok {
			return x.Backup
		}
	}
	return nil
}

func (x *CommandRequest) GetRestart() *RestartCommand {
	if x != nil {
		if x, ok := x.Command.(*CommandRequest_Restart); ok {
			return x.Restart
		}
	}
	return nil
}

func (x *CommandRequest) GetBranch() *BranchCommand {
	if x != nil {
		if x, ok := x.Command.(*CommandRequest_Branch); ok {
			return x.Branch
		}
	}
	return nil
}

func (x *CommandRequest) GetRestore() *RestoreCommand {
	if x != nil {
		if x, ok := x.Command.(*CommandRequest_Restore); ok {
			return x.Restore
		}
	}
	return nil
}

func (x *CommandRequest) GetMigration() *MigrationCommand {
	if x != nil {
		if x, ok := x.Command.(*CommandRequest_Migration); ok {
			return x.Migration
		}
	}
	return nil
}

func (x *CommandRequest) GetValidateIndex() *ValidateIndexCommand {
	if x != nil {
		if x, ok := x.Command.(*CommandRequest_ValidateIndex); ok {
			return x.ValidateIndex
		}
	}
	return nil
}

func (x *CommandRequest) GetPromoteToPrimary() *PromoteToPrimaryCommand {
	if x != nil {
		if x, ok := x.Command.(*CommandRequest_PromoteToPrimary); ok {
			return x.PromoteToPrimary
		}
	}
	return nil
}

func (x *CommandRequest) GetDrDrill() *DRDrillCommand {
	if x != nil {
		if x, ok := x.Command.(*CommandRequest_DrDrill); ok {
			return x.DrDrill
		}
	}
	return nil
}

type isCommandRequest_Command interface {
	isCommandRequest_Command()
}

type CommandRequest_Reconcile struct {
	Reconcile *ReconcileCommand `protobuf:"bytes,2,opt,name=reconcile,proto3,oneof"`
}

type CommandRequest_Backup struct {
	Backup *BackupCommand `protobuf:"bytes,3,opt,name=backup,proto3,oneof"`
}

type CommandRequest_Restart struct {
	Restart *RestartCommand `protobuf:"bytes,4,opt,name=restart,proto3,oneof"`
}

type CommandRequest_Branch struct {
	Branch *BranchCommand `protobuf:"bytes,5,opt,name=branch,proto3,oneof"`
}

type CommandRequest_Restore struct {
	Restore *RestoreCommand `protobuf:"bytes,6,opt,name=restore,proto3,oneof"`
}

type CommandRequest_Migration struct {
	Migration *MigrationCommand `protobuf:"bytes,7,opt,name=migration,proto3,oneof"`
}

type CommandRequest_ValidateIndex struct {
	ValidateIndex *ValidateIndexCommand `protobuf:"bytes,8,opt,name=validate_index,json=validateIndex,proto3,oneof"`
}

type CommandRequest_PromoteToPrimary struct {
	PromoteToPrimary *PromoteToPrimaryCommand `protobuf:"bytes,9,opt,name=promote_to_primary,json=promoteToPrimary,proto3,oneof"`
}

type CommandRequest_DrDrill struct {
	DrDrill *DRDrillCommand `protobuf:"bytes,10,opt,name=dr_drill,json=drDrill,proto3,oneof"`
}

func (*CommandRequest_Reconcile) isCommandRequest_Command() {}

func (*CommandRequest_Backup) isCommandRequest_Command() {}

func (*CommandRequest_Restart) isCommandRequest_Command() {}

func (*CommandRequest_Branch) isCommandRequest_Command() {}

func (*CommandRequest_Restore) isCommandRequest_Command() {}

func (*CommandRequest_Migration) isCommandRequest_Command() {}

func (*CommandRequest_ValidateIndex) isCommandRequest_Command() {}

func (*CommandRequest_PromoteToPrimary) isCommandRequest_Command() {}

func (*CommandRequest_DrDrill) isCommandRequest_Command() {}

type DRDrillCommand struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	DrillId          string                 `protobuf:"bytes,1,opt,name=drill_id,json=drillId,proto3" json:"drill_id,omitempty"`
	SourceSnapshot   string                 `protobuf:"bytes,2,opt,name=source_snapshot,json=sourceSnapshot,proto3" json:"source_snapshot,omitempty"`       // Optional: specific snapshot to test
	ValidationScript string                 `protobuf:"bytes,3,opt,name=validation_script,json=validationScript,proto3" json:"validation_script,omitempty"` // SQL script to run for validation
	TmpPort          int32                  `protobuf:"varint,4,opt,name=tmp_port,json=tmpPort,proto3" json:"tmp_port,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *DRDrillCommand) Reset() {
	*x = DRDrillCommand{}
	mi := &file_proto_agent_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DRDrillCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DRDrillCommand) ProtoMessage() {}

func (x *DRDrillCommand) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DRDrillCommand.ProtoReflect.Descriptor instead.
func (*DRDrillCommand) Descriptor() ([]byte, []int) {
	return file_proto_agent_proto_rawDescGZIP(), []int{2}
}

func (x *DRDrillCommand) GetDrillId() string {
	if x != nil {
		return x.DrillId
	}
	return ""
}

func (x *DRDrillCommand) GetSourceSnapshot() string {
	if x != nil {
		return x.SourceSnapshot
	}
	return ""
}

func (x *DRDrillCommand) GetValidationScript() string {
	if x != nil {
		return x.ValidationScript
	}
	return ""
}

func (x *DRDrillCommand) GetTmpPort() int32 {
	if x != nil {
		return x.TmpPort
	}
	return 0
}

type PromoteToPrimaryCommand struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClusterId     string                 `protobuf:"bytes,1,opt,name=cluster_id,json=clusterId,proto3" json:"cluster_id,omitempty"`
	Force         bool                   `protobuf:"varint,2,opt,name=force,proto3" json:"force,omitempty"` // If true, ignore safety checks (use with caution)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PromoteToPrimaryCommand) Reset() {
	*x = PromoteToPrimaryCommand{}
	mi := &file_proto_agent_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PromoteToPrimaryCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PromoteToPrimaryCommand) ProtoMessage() {}

func (x *PromoteToPrimaryCommand) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PromoteToPrimaryCommand.ProtoReflect.Descriptor instead.
func (*PromoteToPrimaryCommand) Descriptor() ([]byte, []int) {
	return file_proto_agent_proto_rawDescGZIP(), []int{3}
}

func (x *PromoteToPrimaryCommand) GetClusterId() string {
	if x != nil {
		return x.ClusterId
	}
	return ""
}

func (x *PromoteToPrimaryCommand) GetForce() bool {
	if x != nil {
		return x.Force
	}
	return false
}

type ValidateIndexCommand struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ValidationId    string                 `protobuf:"bytes,1,opt,name=validation_id,json=validationId,proto3" json:"validation_id,omitempty"`
	TableName       string                 `protobuf:"bytes,2,opt,name=table_name,json=tableName,proto3" json:"table_name,omitempty"`
	IndexDefinition string                 `protobuf:"bytes,3,opt,name=index_definition,json=indexDefinition,proto3" json:"index_definition,omitempty"`
	SampleQuery     string                 `protobuf:"bytes,4,opt,name=sample_query,json=sampleQuery,proto3" json:"sample_query,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ValidateIndexCommand) Reset() {
	*x = ValidateIndexCommand{}
	mi := &file_proto_agent_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateIndexCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateIndexCommand) ProtoMessage() {}

func (x *ValidateIndexCommand) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateIndexCommand.ProtoReflect.Descriptor instead.
func (*ValidateIndexCommand) Descriptor() ([]byte, []int) {
	return file_proto_agent_proto_rawDescGZIP(), []int{4}
}

func (x *ValidateIndexCommand) GetValidationId() string {
	if x != nil {
		return x.ValidationId
	}
	return ""
}

func (x *ValidateIndexCommand) GetTableName() string {
	if x != nil {
		return x.TableName
	}
	return ""
}

func (x *ValidateIndexCommand) GetIndexDefinition() string {
	if x != nil {
		return x.IndexDefinition
	}
	return ""
}

func (x *ValidateIndexCommand) GetSampleQuery() string {
	if x != nil {
		return x.SampleQuery
	}
	return ""
}

type MigrationCommand struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MigrationId   string                 `protobuf:"bytes,1,opt,name=migration_id,json=migrationId,proto3" json:"migration_id,omitempty"`
	Phase         string                 `protobuf:"bytes,2,opt,name=phase,proto3" json:"phase,omitempty"` // pre-flight, schema, full-load, cdc, cutover
	Config        *structpb.Struct       `protobuf:"bytes,3,opt,name=config,proto3" json:"config,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MigrationCommand) Reset() {
	*x = MigrationCommand{}
	mi := &file_proto_agent_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MigrationCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MigrationCommand) ProtoMessage() {}

func (x *MigrationCommand) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MigrationCommand.ProtoReflect.Descriptor instead.
func (*MigrationCommand) Descriptor() ([]byte, []int) {
	return file_proto_agent_proto_rawDescGZIP(), []int{5}
}

func (x *MigrationCommand) GetMigrationId() string {
	if x != nil {
		return x.MigrationId
	}
	return ""
}

func (x *MigrationCommand) GetPhase() string {
	if x != nil {
		return x.Phase
	}
	return ""
}

func (x *MigrationCommand) GetConfig() *structpb.Struct {
	if x != nil {
		return x.Config
	}
	return nil
}

type CommandResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CommandId     string                 `protobuf:"bytes,1,opt,name=command_id,json=commandId,proto3" json:"command_id,omitempty"`
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,3,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	Output        *structpb.Struct       `protobuf:"bytes,4,opt,name=output,proto3" json:"output,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommandResult) Reset() {
	*x = CommandResult{}
	mi := &file_proto_agent_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommandResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommandResult) ProtoMessage() {}

func (x *CommandResult) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommandResult.ProtoReflect.Descriptor instead.
func (*CommandResult) Descriptor() ([]byte, []int) {
	return file_proto_agent_proto_rawDescGZIP(), []int{6}
}

func (x *CommandResult) GetCommandId() string {
	if x != nil {
		return x.CommandId
	}
	return ""
}

func (x *CommandResult) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CommandResult) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *CommandResult) GetOutput() *structpb.Struct {
	if x != nil {
		return x.Output
	}
	return nil
}

// ReconcileCommand provides the 'Desired State' manifest.
type ReconcileCommand struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The desired state manifest (JSON/YAML structure).
	DesiredState  *structpb.Struct `protobuf:"bytes,1,opt,name=desired_state,json=desiredState,proto3" json:"desired_state,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReconcileCommand) Reset() {
	*x = ReconcileCommand{}
	mi := &file_proto_agent_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReconcileCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReconcileCommand) ProtoMessage() {}

func (x *ReconcileCommand) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReconcileCommand.ProtoReflect.Descriptor instead.
func (*ReconcileCommand) Descriptor() ([]byte, []int) {
	return file_proto_agent_proto_rawDescGZIP(), []int{7}
}

func (x *ReconcileCommand) GetDesiredState() *structpb.Struct {
	if x != nil {
		return x.DesiredState
	}
	return nil
}

type BackupCommand struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	BackupId string                 `protobuf:"bytes,1,opt,name=backup_id,json=backupId,proto3" json:"backup_id,omitempty"`
	// Type can be "full", "incremental", or "differential".
	Type          string `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BackupCommand) Reset() {
	*x = BackupCommand{}
	mi := &file_proto_agent_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BackupCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BackupCommand) ProtoMessage() {}

func (x *BackupCommand) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BackupCommand.ProtoReflect.Descriptor instead.
func (*BackupCommand) Descriptor() ([]byte, []int) {
	return file_proto_agent_proto_rawDescGZIP(), []int{8}
}

func (x *BackupCommand) GetBackupId() string {
	if x != nil {
		return x.BackupId
	}
	return ""
}

func (x *BackupCommand) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

type RestartCommand struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The service name (e.g., "postgresql", "patroni", "agent").
	Service       string `protobuf:"bytes,1,opt,name=service,proto3" json:"service,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RestartCommand) Reset() {
	*x = RestartCommand{}
	mi := &file_proto_agent_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RestartCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RestartCommand) ProtoMessage() {}

func (x *RestartCommand) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RestartCommand.ProtoReflect.Descriptor instead.
func (*RestartCommand) Descriptor() ([]byte, []int) {
	return file_proto_agent_proto_rawDescGZIP(), []int{9}
}

func (x *RestartCommand) GetService() string {
	if x != nil {
		return x.Service
	}
	return ""
}

type BranchCommand struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	BranchId       string                 `protobuf:"bytes,1,opt,name=branch_id,json=branchId,proto3" json:"branch_id,omitempty"`
	SourceSnapshot string                 `protobuf:"bytes,2,opt,name=source_snapshot,json=sourceSnapshot,proto3" json:"source_snapshot,omitempty"`
	TargetName     string                 `protobuf:"bytes,3,opt,name=target_name,json=targetName,proto3" json:"target_name,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *BranchCommand) Reset() {
	*x = BranchCommand{}
	mi := &file_proto_agent_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BranchCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BranchCommand) ProtoMessage() {}

func (x *BranchCommand) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BranchCommand.ProtoReflect.Descriptor instead.
func (*BranchCommand) Descriptor() ([]byte, []int) {
	return file_proto_agent_proto_rawDescGZIP(), []int{10}
}

func (x *BranchCommand) GetBranchId() string {
	if x != nil {
		return x.BranchId
	}
	return ""
}

func (x *BranchCommand) GetSourceSnapshot() string {
	if x != nil {
		return x.SourceSnapshot
	}
	return ""
}

func (x *BranchCommand) GetTargetName() string {
	if x != nil {
		return x.TargetName
	}
	return ""
}

type RestoreCommand struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RestoreId     string                 `protobuf:"bytes,1,opt,name=restore_id,json=restoreId,proto3" json:"restore_id,omitempty"`
	TargetTime    *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=target_time,json=targetTime,proto3" json:"target_time,omitempty"`
	TargetLsn     string                 `protobuf:"bytes,3,opt,name=target_lsn,json=targetLsn,proto3" json:"target_lsn,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RestoreCommand) Reset() {
	*x = RestoreCommand{}
	mi := &file_proto_agent_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RestoreCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RestoreCommand) ProtoMessage() {}

func (x *RestoreCommand) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RestoreCommand.ProtoReflect.Descriptor instead.
func (*RestoreCommand) Descriptor() ([]byte, []int) {
	return file_proto_agent_proto_rawDescGZIP(), []int{11}
}

func (x *RestoreCommand) GetRestoreId() string {
	if x != nil {
		return x.RestoreId
	}
	return ""
}

func (x *RestoreCommand) GetTargetTime() *timestamppb.Timestamp {
	if x != nil {
		return x.TargetTime
	}
	return nil
}

func (x *RestoreCommand) GetTargetLsn() string {
	if x != nil {
		return x.TargetLsn
	}
	return ""
}

type LogBatch struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	Entries       []*LogEntry            `protobuf:"bytes,2,rep,name=entries,proto3" json:"entries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogBatch) Reset() {
	*x = LogBatch{}
	mi := &file_proto_agent_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogBatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogBatch) ProtoMessage() {}

func (x *LogBatch) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogBatch.ProtoReflect.Descriptor instead.
func (*LogBatch) Descriptor() ([]byte, []int) {
	return file_proto_agent_proto_rawDescGZIP(), []int{12}
}

func (x *LogBatch) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *LogBatch) GetEntries() []*LogEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

type LogEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Level         string                 `protobuf:"bytes,2,opt,name=level,proto3" json:"level,omitempty"` // e.g., "INFO", "ERROR", "FATAL"
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	Metadata      *structpb.Struct       `protobuf:"bytes,4,opt,name=metadata,proto3" json:"metadata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogEntry) Reset() {
	*x = LogEntry{}
	mi := &file_proto_agent_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogEntry) ProtoMessage() {}

func (x *LogEntry) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogEntry.ProtoReflect.Descriptor instead.
func (*LogEntry) Descriptor() ([]byte, []int) {
	return file_proto_agent_proto_rawDescGZIP(), []int{13}
}

func (x *LogEntry) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *LogEntry) GetLevel() string {
	if x != nil {
		return x.Level
	}
	return ""
}

func (x *LogEntry) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *LogEntry) GetMetadata() *structpb.Struct {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type MetricBatch struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	Entries       []*MetricEntry         `protobuf:"bytes,2,rep,name=entries,proto3" json:"entries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MetricBatch) Reset() {
	*x = MetricBatch{}
	mi := &file_proto_agent_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetricBatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetricBatch) ProtoMessage() {}

func (x *MetricBatch) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetricBatch.ProtoReflect.Descriptor instead.
func (*MetricBatch) Descriptor() ([]byte, []int) {
	return file_proto_agent_proto_rawDescGZIP(), []int{14}
}

func (x *MetricBatch) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *MetricBatch) GetEntries() []*MetricEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

type MetricEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Value         float64                `protobuf:"fixed64,2,opt,name=value,proto3" json:"value,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Labels        map[string]string      `protobuf:"bytes,4,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MetricEntry) Reset() {
	*x = MetricEntry{}
	mi := &file_proto_agent_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetricEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetricEntry) ProtoMessage() {}

func (x *MetricEntry) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetricEntry.ProtoReflect.Descriptor instead.
func (*MetricEntry) Descriptor() ([]byte, []int) {
	return file_proto_agent_proto_rawDescGZIP(), []int{15}
}

func (x *MetricEntry) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *MetricEntry) GetValue() float64 {
	if x != nil {
		return x.Value
	}
	return 0
}

func (x *MetricEntry) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *MetricEntry) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

type PushResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,2,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PushResponse) Reset() {
	*x = PushResponse{}
	mi := &file_proto_agent_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PushResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushResponse) ProtoMessage() {}

func (x *PushResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushResponse.ProtoReflect.Descriptor instead.
func (*PushResponse) Descriptor() ([]byte, []int) {
	return file_proto_agent_proto_rawDescGZIP(), []int{16}
}

func (x *PushResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *PushResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

var File_proto_agent_proto protoreflect.FileDescriptor

const file_proto_agent_proto_rawDesc = "" +
	"\n" +
	"\x11proto/agent.proto\x12\x0eaxiom.agent.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1cgoogle/protobuf/struct.proto\"\x94\x02\n" +
	"\x10HeartbeatRequest\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x128\n" +
	"\ttimestamp\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x124\n" +
	"\x06status\x18\x03 \x01(\x0e2\x1c.axiom.agent.v1.HealthStatusR\x06status\x12<\n" +
	"\rcurrent_state\x18\x04 \x01(\v2\x17.google.protobuf.StructR\fcurrentState\x127\n" +
	"\aresults\x18\x05 \x03(\v2\x1d.axiom.agent.v1.CommandResultR\aresults\"\x8d\x05\n" +
	"\x0eCommandRequest\x12\x1d\n" +
	"\n" +
	"command_id\x18\x01 \x01(\tR\tcommandId\x12@\n" +
	"\treconcile\x18\x02 \x01(\v2 .axiom.agent.v1.ReconcileCommandH\x00R\treconcile\x127\n" +
	"\x06backup\x18\x03 \x01(\v2\x1d.axiom.agent.v1.BackupCommandH\x00R\x06backup\x12:\n" +
	"\arestart\x18\x04 \x01(\v2\x1e.axiom.agent.v1.RestartCommandH\x00R\arestart\x127\n" +
	"\x06branch\x18\x05 \x01(\v2\x1d.axiom.agent.v1.BranchCommandH\x00R\x06branch\x12:\n" +
	"\arestore\x18\x06 \x01(\v2\x1e.axiom.agent.v1.RestoreCommandH\x00R\arestore\x12@\n" +
	"\tmigration\x18\a \x01(\v2 .axiom.agent.v1.MigrationCommandH\x00R\tmigration\x12M\n" +
	"\x0evalidate_index\x18\b \x01(\v2$.axiom.agent.v1.ValidateIndexCommandH\x00R\rvalidateIndex\x12W\n" +
	"\x12promote_to_primary\x18\t \x01(\v2'.axiom.agent.v1.PromoteToPrimaryCommandH\x00R\x10promoteToPrimary\x12;\n" +
	"\bdr_drill\x18\n" +
	" \x01(\v2\x1e.axiom.agent.v1.DRDrillCommandH\x00R\adrDrillB\t\n" +
	"\acommand\"\x9c\x01\n" +
	"\x0eDRDrillCommand\x12\x19\n" +
	"\bdrill_id\x18\x01 \x01(\tR\adrillId\x12'\n" +
	"\x0fsource_snapshot\x18\x02 \x01(\tR\x0esourceSnapshot\x12+\n" +
	"\x11validation_script\x18\x03 \x01(\tR\x10validationScript\x12\x19\n" +
	"\btmp_port\x18\x04 \x01(\x05R\atmpPort\"N\n" +
	"\x17PromoteToPrimaryCommand\x12\x1d\n" +
	"\n" +
	"cluster_id\x18\x01 \x01(\tR\tclusterId\x12\x14\n" +
	"\x05force\x18\x02 \x01(\bR\x05force\"\xa8\x01\n" +
	"\x14ValidateIndexCommand\x12#\n" +
	"\rvalidation_id\x18\x01 \x01(\tR\fvalidationId\x12\x1d\n" +
	"\n" +
	"table_name\x18\x02 \x01(\tR\ttableName\x12)\n" +
	"\x10index_definition\x18\x03 \x01(\tR\x0findexDefinition\x12!\n" +
	"\fsample_query\x18\x04 \x01(\tR\vsampleQuery\"|\n" +
	"\x10MigrationCommand\x12!\n" +
	"\fmigration_id\x18\x01 \x01(\tR\vmigrationId\x12\x14\n" +
	"\x05phase\x18\x02 \x01(\tR\x05phase\x12/\n" +
	"\x06config\x18\x03 \x01(\v2\x17.google.protobuf.StructR\x06config\"\x9e\x01\n" +
	"\rCommandResult\x12\x1d\n" +
	"\n" +
	"command_id\x18\x01 \x01(\tR\tcommandId\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\x12#\n" +
	"\rerror_message\x18\x03 \x01(\tR\ferrorMessage\x12/\n" +
	"\x06output\x18\x04 \x01(\v2\x17.google.protobuf.StructR\x06output\"P\n" +
	"\x10ReconcileCommand\x12<\n" +
	"\rdesired_state\x18\x01 \x01(\v2\x17.google.protobuf.StructR\fdesiredState\"@\n" +
	"\rBackupCommand\x12\x1b\n" +
	"\tbackup_id\x18\x01 \x01(\tR\bbackupId\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\"*\n" +
	"\x0eRestartCommand\x12\x18\n" +
	"\aservice\x18\x01 \x01(\tR\aservice\"v\n" +
	"\rBranchCommand\x12\x1b\n" +
	"\tbranch_id\x18\x01 \x01(\tR\bbranchId\x12'\n" +
	"\x0fsource_snapshot\x18\x02 \x01(\tR\x0esourceSnapshot\x12\x1f\n" +
	"\vtarget_name\x18\x03 \x01(\tR\n" +
	"targetName\"\x8b\x01\n" +
	"\x0eRestoreCommand\x12\x1d\n" +
	"\n" +
	"restore_id\x18\x01 \x01(\tR\trestoreId\x12;\n" +
	"\vtarget_time\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"targetTime\x12\x1d\n" +
	"\n" +
	"target_lsn\x18\x03 \x01(\tR\ttargetLsn\"Y\n" +
	"\bLogBatch\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x122\n" +
	"\aentries\x18\x02 \x03(\v2\x18.axiom.agent.v1.LogEntryR\aentries\"\xa9\x01\n" +
	"\bLogEntry\x128\n" +
	"\ttimestamp\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12\x14\n" +
	"\x05level\x18\x02 \x01(\tR\x05level\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x123\n" +
	"\bmetadata\x18\x04 \x01(\v2\x17.google.protobuf.StructR\bmetadata\"_\n" +
	"\vMetricBatch\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x125\n" +
	"\aentries\x18\x02 \x03(\v2\x1b.axiom.agent.v1.MetricEntryR\aentries\"\xed\x01\n" +
	"\vMetricEntry\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x01R\x05value\x128\n" +
	"\ttimestamp\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12?\n" +
	"\x06labels\x18\x04 \x03(\v2'.axiom.agent.v1.MetricEntry.LabelsEntryR\x06labels\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"M\n" +
	"\fPushResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12#\n" +
	"\rerror_message\x18\x02 \x01(\tR\ferrorMessage*\x81\x01\n" +
	"\fHealthStatus\x12\x1d\n" +
	"\x19HEALTH_STATUS_UNSPECIFIED\x10\x00\x12\x19\n" +
	"\x15HEALTH_STATUS_HEALTHY\x10\x01\x12\x1a\n" +
	"\x16HEALTH_STATUS_DEGRADED\x10\x02\x12\x1b\n" +
	"\x17HEALTH_STATUS_UNHEALTHY\x10\x032\xf1\x01\n" +
	"\fAxiomService\x12O\n" +
	"\aConnect\x12 .axiom.agent.v1.HeartbeatRequest\x1a\x1e.axiom.agent.v1.CommandRequest(\x010\x01\x12D\n" +
	"\bPushLogs\x12\x18.axiom.agent.v1.LogBatch\x1a\x1c.axiom.agent.v1.PushResponse(\x01\x12J\n" +
	"\vPushMetrics\x12\x1b.axiom.agent.v1.MetricBatch\x1a\x1c.axiom.agent.v1.PushResponse(\x01B.Z,github.com/axiom/axiom-center/proto/agent/v1b\x06proto3"

var (
	file_proto_agent_proto_rawDescOnce sync.Once
	file_proto_agent_proto_rawDescData []byte
)

func file_proto_agent_proto_rawDescGZIP() []byte {
	file_proto_agent_proto_rawDescOnce.Do(func() {
		file_proto_agent_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_agent_proto_rawDesc), len(file_proto_agent_proto_rawDesc)))
	})
	return file_proto_agent_proto_rawDescData
}

var file_proto_agent_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_agent_proto_msgTypes = make([]protoimpl.MessageInfo, 18)
var file_proto_agent_proto_goTypes = []any{
	(HealthStatus)(0),               // 0: axiom.agent.v1.HealthStatus
	(*HeartbeatRequest)(nil),        // 1: axiom.agent.v1.HeartbeatRequest
	(*CommandRequest)(nil),          // 2: axiom.agent.v1.CommandRequest
	(*DRDrillCommand)(nil),          // 3: axiom.agent.v1.DRDrillCommand
	(*PromoteToPrimaryCommand)(nil), // 4: axiom.agent.v1.PromoteToPrimaryCommand
	(*ValidateIndexCommand)(nil),    // 5: axiom.agent.v1.ValidateIndexCommand
	(*MigrationCommand)(nil),        // 6: axiom.agent.v1.MigrationCommand
	(*CommandResult)(nil),           // 7: axiom.agent.v1.CommandResult
	(*ReconcileCommand)(nil),        // 8: axiom.agent.v1.ReconcileCommand
	(*BackupCommand)(nil),           // 9: axiom.agent.v1.BackupCommand
	(*RestartCommand)(nil),          // 10: axiom.agent.v1.RestartCommand
	(*BranchCommand)(nil),           // 11: axiom.agent.v1.BranchCommand
	(*RestoreCommand)(nil),          // 12: axiom.agent.v1.RestoreCommand
	(*LogBatch)(nil),                // 13: axiom.agent.v1.LogBatch
	(*LogEntry)(nil),                // 14: axiom.agent.v1.LogEntry
	(*MetricBatch)(nil),             // 15: axiom.agent.v1.MetricBatch
	(*MetricEntry)(nil),             // 16: axiom.agent.v1.MetricEntry
	(*PushResponse)(nil),            // 17: axiom.agent.v1.PushResponse
	nil,                             // 18: axiom.agent.v1.MetricEntry.LabelsEntry
	(*timestamppb.Timestamp)(nil),   // 19: google.protobuf.Timestamp
	(*structpb.Struct)(nil),         // 20: google.protobuf.Struct
}
var file_proto_agent_proto_depIdxs = []int32{
	19, // 0: axiom.agent.v1.HeartbeatRequest.timestamp:type_name -> google.protobuf.Timestamp
	0,  // 1: axiom.agent.v1.HeartbeatRequest.status:type_name -> axiom.agent.v1.HealthStatus
	20, // 2: axiom.agent.v1.HeartbeatRequest.current_state:type_name -> google.protobuf.Struct
	7,  // 3: axiom.agent.v1.HeartbeatRequest.results:type_name -> axiom.agent.v1.CommandResult
	8,  // 4: axiom.agent.v1.CommandRequest.reconcile:type_name -> axiom.agent.v1.ReconcileCommand
	9,  // 5: axiom.agent.v1.CommandRequest.backup:type_name -> axiom.agent.v1.BackupCommand
	10, // 6: axiom.agent.v1.CommandRequest.restart:type_name -> axiom.agent.v1.RestartCommand
	11, // 7: axiom.agent.v1.CommandRequest.branch:type_name -> axiom.agent.v1.BranchCommand
	12, // 8: axiom.agent.v1.CommandRequest.restore:type_name -> axiom.agent.v1.RestoreCommand
	6,  // 9: axiom.agent.v1.CommandRequest.migration:type_name -> axiom.agent.v1.MigrationCommand
	5,  // 10: axiom.agent.v1.CommandRequest.validate_index:type_name -> axiom.agent.v1.ValidateIndexCommand
	4,  // 11: axiom.agent.v1.CommandRequest.promote_to_primary:type_name -> axiom.agent.v1.PromoteToPrimaryCommand
	3,  // 12: axiom.agent.v1.CommandRequest.dr_drill:type_name -> axiom.agent.v1.DRDrillCommand
	20, // 13: axiom.agent.v1.MigrationCommand.config:type_name -> google.protobuf.Struct
	20, // 14: axiom.agent.v1.CommandResult.output:type_name -> google.protobuf.Struct
	20, // 15: axiom.agent.v1.ReconcileCommand.desired_state:type_name -> google.protobuf.Struct
	19, // 16: axiom.agent.v1.RestoreCommand.target_time:type_name -> google.protobuf.Timestamp
	14, // 17: axiom.agent.v1.LogBatch.entries:type_name -> axiom.agent.v1.LogEntry
	19, // 18: axiom.agent.v1.LogEntry.timestamp:type_name -> google.protobuf.Timestamp
	20, // 19: axiom.agent.v1.LogEntry.metadata:type_name -> google.protobuf.Struct
	16, // 20: axiom.agent.v1.MetricBatch.entries:type_name -> axiom.agent.v1.MetricEntry
	19, // 21: axiom.agent.v1.MetricEntry.timestamp:type_name -> google.protobuf.Timestamp
	18, // 22: axiom.agent.v1.MetricEntry.labels:type_name -> axiom.agent.v1.MetricEntry.LabelsEntry
	1,  // 23: axiom.agent.v1.AxiomService.Connect:input_type -> axiom.agent.v1.HeartbeatRequest
	13, // 24: axiom.agent.v1.AxiomService.PushLogs:input_type -> axiom.agent.v1.LogBatch
	15, // 25: axiom.agent.v1.AxiomService.PushMetrics:input_type -> axiom.agent.v1.MetricBatch
	2,  // 26: axiom.agent.v1.AxiomService.Connect:output_type -> axiom.agent.v1.CommandRequest
	17, // 27: axiom.agent.v1.AxiomService.PushLogs:output_type -> axiom.agent.v1.PushResponse
	17, // 28: axiom.agent.v1.AxiomService.PushMetrics:output_type -> axiom.agent.v1.PushResponse
	26, // [26:29] is the sub-list for method output_type
	23, // [23:26] is the sub-list for method input_type
	23, // [23:23] is the sub-list for extension type_name
	23, // [23:23] is the sub-list for extension extendee
	0,  // [0:23] is the sub-list for field type_name
}

func init() { file_proto_agent_proto_init() }
func file_proto_agent_proto_init() {
	if File_proto_agent_proto != nil {
		return
	}
	file_proto_agent_proto_msgTypes[1].OneofWrappers = []any{
		(*CommandRequest_Reconcile)(nil),
		(*CommandRequest_Backup)(nil),
		(*CommandRequest_Restart)(nil),
		(*CommandRequest_Branch)(nil),
		(*CommandRequest_Restore)(nil),
		(*CommandRequest_Migration)(nil),
		(*CommandRequest_ValidateIndex)(nil),
		(*CommandRequest_PromoteToPrimary)(nil),
		(*CommandRequest_DrDrill)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_agent_proto_rawDesc), len(file_proto_agent_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   18,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_agent_proto_goTypes,
		DependencyIndexes: file_proto_agent_proto_depIdxs,
		EnumInfos:         file_proto_agent_proto_enumTypes,
		MessageInfos:      file_proto_agent_proto_msgTypes,
	}.Build()
	File_proto_agent_proto = out.File
	file_proto_agent_proto_goTypes = nil
	file_proto_agent_proto_depIdxs = nil
}
