// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v3.21.12
// source: proto/agent.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AxiomService_Connect_FullMethodName     = "/axiom.agent.v1.AxiomService/Connect"
	AxiomService_PushLogs_FullMethodName    = "/axiom.agent.v1.AxiomService/PushLogs"
	AxiomService_PushMetrics_FullMethodName = "/axiom.agent.v1.AxiomService/PushMetrics"
)

// AxiomServiceClient is the client API for AxiomService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// AxiomService is the main interface for communication between the Axiom Agent and Axiom Center.
type AxiomServiceClient interface {
	// Connect establishes a long-lived bidirectional stream for heartbeats and command delivery.
	// The Agent (client) initiates the connection.
	Connect(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[HeartbeatRequest, CommandRequest], error)
	// PushLogs allows the Agent to stream PostgreSQL and system logs to the Center.
	PushLogs(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[LogBatch, PushResponse], error)
	// PushMetrics allows the Agent to stream telemetry data to the Center.
	PushMetrics(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[MetricBatch, PushResponse], error)
}

type axiomServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAxiomServiceClient(cc grpc.ClientConnInterface) AxiomServiceClient {
	return &axiomServiceClient{cc}
}

func (c *axiomServiceClient) Connect(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[HeartbeatRequest, CommandRequest], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &AxiomService_ServiceDesc.Streams[0], AxiomService_Connect_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[HeartbeatRequest, CommandRequest]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AxiomService_ConnectClient = grpc.BidiStreamingClient[HeartbeatRequest, CommandRequest]

func (c *axiomServiceClient) PushLogs(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[LogBatch, PushResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &AxiomService_ServiceDesc.Streams[1], AxiomService_PushLogs_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[LogBatch, PushResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AxiomService_PushLogsClient = grpc.ClientStreamingClient[LogBatch, PushResponse]

func (c *axiomServiceClient) PushMetrics(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[MetricBatch, PushResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &AxiomService_ServiceDesc.Streams[2], AxiomService_PushMetrics_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[MetricBatch, PushResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AxiomService_PushMetricsClient = grpc.ClientStreamingClient[MetricBatch, PushResponse]

// AxiomServiceServer is the server API for AxiomService service.
// All implementations must embed UnimplementedAxiomServiceServer
// for forward compatibility.
//
// AxiomService is the main interface for communication between the Axiom Agent and Axiom Center.
type AxiomServiceServer interface {
	// Connect establishes a long-lived bidirectional stream for heartbeats and command delivery.
	// The Agent (client) initiates the connection.
	Connect(grpc.BidiStreamingServer[HeartbeatRequest, CommandRequest]) error
	// PushLogs allows the Agent to stream PostgreSQL and system logs to the Center.
	PushLogs(grpc.ClientStreamingServer[LogBatch, PushResponse]) error
	// PushMetrics allows the Agent to stream telemetry data to the Center.
	PushMetrics(grpc.ClientStreamingServer[MetricBatch, PushResponse]) error
	mustEmbedUnimplementedAxiomServiceServer()
}

// UnimplementedAxiomServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAxiomServiceServer struct{}

func (UnimplementedAxiomServiceServer) Connect(grpc.BidiStreamingServer[HeartbeatRequest, CommandRequest]) error {
	return status.Error(codes.Unimplemented, "method Connect not implemented")
}
func (UnimplementedAxiomServiceServer) PushLogs(grpc.ClientStreamingServer[LogBatch, PushResponse]) error {
	return status.Error(codes.Unimplemented, "method PushLogs not implemented")
}
func (UnimplementedAxiomServiceServer) PushMetrics(grpc.ClientStreamingServer[MetricBatch, PushResponse]) error {
	return status.Error(codes.Unimplemented, "method PushMetrics not implemented")
}
func (UnimplementedAxiomServiceServer) mustEmbedUnimplementedAxiomServiceServer() {}
func (UnimplementedAxiomServiceServer) testEmbeddedByValue()                      {}

// UnsafeAxiomServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AxiomServiceServer will
// result in compilation errors.
type UnsafeAxiomServiceServer interface {
	mustEmbedUnimplementedAxiomServiceServer()
}

func RegisterAxiomServiceServer(s grpc.ServiceRegistrar, srv AxiomServiceServer) {
	// If the following call panics, it indicates UnimplementedAxiomServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AxiomService_ServiceDesc, srv)
}

func _AxiomService_Connect_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(AxiomServiceServer).Connect(&grpc.GenericServerStream[HeartbeatRequest, CommandRequest]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AxiomService_ConnectServer = grpc.BidiStreamingServer[HeartbeatRequest, CommandRequest]

func _AxiomService_PushLogs_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(AxiomServiceServer).PushLogs(&grpc.GenericServerStream[LogBatch, PushResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AxiomService_PushLogsServer = grpc.ClientStreamingServer[LogBatch, PushResponse]

func _AxiomService_PushMetrics_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(AxiomServiceServer).PushMetrics(&grpc.GenericServerStream[MetricBatch, PushResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AxiomService_PushMetricsServer = grpc.ClientStreamingServer[MetricBatch, PushResponse]

// AxiomService_ServiceDesc is the grpc.ServiceDesc for AxiomService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AxiomService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "axiom.agent.v1.AxiomService",
	HandlerType: (*AxiomServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Connect",
			Handler:       _AxiomService_Connect_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "PushLogs",
			Handler:       _AxiomService_PushLogs_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "PushMetrics",
			Handler:       _AxiomService_PushMetrics_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "proto/agent.proto",
}
