package agent

import (
	"bufio"
	"crypto/md5"
	"database/sql"
	"encoding/hex"
	"fmt"
	"log"
	"os"
	"os/exec"
	"path/filepath"
	"sync"
	"syscall"
	"time"

	_ "github.com/lib/pq"
)

// PoolConfig holds the settings needed to launch and manage pgbouncer.
type PoolConfig struct {
	BinaryPath string // path to pgbouncer binary, e.g. "/usr/sbin/pgbouncer"
	ConfigPath string // path to pgbouncer.ini (generated by GenerateIni, not hand-written)
	ListenPort int

	// --- new fields for Phase 1.1 ---
	AdminPort       int    // pgbouncer admin console port (usually same as ListenPort, db "pgbouncer")
	AdminDSN        string // DSN used to connect to the admin console, e.g. "host=127.0.0.1 port=6432 dbname=pgbouncer user=pgbouncer sslmode=disable"
	PoolMode        string // "session", "transaction", or "statement"
	MaxClientConn   int
	DefaultPoolSize int
	MinPoolSize     int
	AuthType        string // e.g. "md5", "scram-sha-256"
	AuthFile        string // path to userlist.txt

	// Postgres credentials the pool authenticates real clients against
	PgUser     string
	PgPassword string

	// Upstream database this pool fronts
	UpstreamHost string
	UpstreamPort int
	UpstreamDB   string

	// --- new fields for Phase 1.2 (async stats shipping) ---
	StatsPollInterval time.Duration // how often to poll SHOW STATS / SHOW POOLS
	StatsLogPath      string        // where shipped stats get written (async, never blocks pooling)
	StatsBufferSize   int           // channel buffer size before we start dropping
}

// PoolManager supervises a single pgbouncer subprocess.
type PoolManager struct {
	mu     sync.Mutex
	cmd    *exec.Cmd
	status string
	Config PoolConfig

	// stats pipeline state
	statsCh       chan string
	droppedStats  int64
	statsDone     chan struct{}
	statsWG       sync.WaitGroup
}

// NewPoolManager constructs a PoolManager with the given config.
func NewPoolManager(cfg PoolConfig) *PoolManager {
	if cfg.StatsPollInterval == 0 {
		cfg.StatsPollInterval = 5 * time.Second
	}
	if cfg.StatsBufferSize == 0 {
		cfg.StatsBufferSize = 256
	}
	return &PoolManager{
		Config: cfg,
		status: "stopped",
	}
}

// GenerateIni writes a real pgbouncer.ini to pm.Config.ConfigPath based on
// the struct fields, instead of assuming a hand-maintained file already
// exists. This closes the same class of gap that Patroni's config
// generation had (silent assumption that a file was already there).
func (pm *PoolManager) GenerateIni() error {
	if pm.Config.ConfigPath == "" {
		return fmt.Errorf("ConfigPath is empty, cannot generate pgbouncer.ini")
	}

	poolMode := pm.Config.PoolMode
	if poolMode == "" {
		poolMode = "transaction"
	}
	maxClientConn := pm.Config.MaxClientConn
	if maxClientConn == 0 {
		maxClientConn = 200
	}
	defaultPoolSize := pm.Config.DefaultPoolSize
	if defaultPoolSize == 0 {
		defaultPoolSize = 20
	}
	authType := pm.Config.AuthType
	if authType == "" {
		authType = "md5"
	}

	ini := fmt.Sprintf(`[databases]
%s = host=%s port=%d dbname=%s

[pgbouncer]
listen_port = %d
listen_addr = 127.0.0.1
auth_type = %s
auth_file = %s
pool_mode = %s
max_client_conn = %d
default_pool_size = %d
min_pool_size = %d
admin_users = postgres
stats_period = %d
`,
		pm.Config.UpstreamDB, pm.Config.UpstreamHost, pm.Config.UpstreamPort, pm.Config.UpstreamDB,
		pm.Config.ListenPort,
		authType, pm.Config.AuthFile,
		poolMode, maxClientConn, defaultPoolSize, pm.Config.MinPoolSize,
		int(pm.Config.StatsPollInterval.Seconds()),
	)

	// Atomic write: temp file + rename, so a crash mid-write never leaves
	// a truncated/corrupt config for pgbouncer to read on next start.
	tmpPath := pm.Config.ConfigPath + ".tmp"
	if err := os.WriteFile(tmpPath, []byte(ini), 0644); err != nil {
		return fmt.Errorf("failed to write temp pgbouncer.ini: %w", err)
	}
	if err := os.Rename(tmpPath, pm.Config.ConfigPath); err != nil {
		return fmt.Errorf("failed to move pgbouncer.ini into place: %w", err)
	}
	return nil
}

// Start launches the managed pgbouncer process and verifies it stays alive
// briefly before reporting success. It also spawns a background reaper so
// pm.status reflects reality if the process dies later, and starts the
// decoupled stats-shipping pipeline (Phase 1.2).
func (pm *PoolManager) Start() error {
	pm.mu.Lock()
	defer pm.mu.Unlock()

	if pm.cmd != nil && pm.cmd.Process != nil {
		return fmt.Errorf("pgbouncer already running (pid %d)", pm.cmd.Process.Pid)
	}

	cmd := exec.Command(pm.Config.BinaryPath, pm.Config.ConfigPath)
	if err := cmd.Start(); err != nil {
		return fmt.Errorf("failed to start pgbouncer: %v", err)
	}

	// Give it a moment, then confirm it's actually alive (not dead/zombie)
	// before declaring success. A PID alone is not proof of life.
	time.Sleep(300 * time.Millisecond)
	if err := cmd.Process.Signal(syscall.Signal(0)); err != nil {
		return fmt.Errorf("pgbouncer exited immediately after start: %v", err)
	}

	pm.cmd = cmd
	pm.status = "running"

	go func() {
		_ = cmd.Wait()
		pm.mu.Lock()
		pm.status = "stopped"
		pm.cmd = nil
		pm.mu.Unlock()
	}()

	pm.startStatsPipeline()

	return nil
}

// Stop gracefully terminates the managed pgbouncer process and the stats
// pipeline that was shipping its telemetry.
func (pm *PoolManager) Stop() error {
	pm.mu.Lock()
	defer pm.mu.Unlock()

	pm.stopStatsPipeline()

	if pm.cmd == nil || pm.cmd.Process == nil {
		return nil
	}

	if err := pm.cmd.Process.Signal(syscall.SIGTERM); err != nil {
		return fmt.Errorf("failed to stop pgbouncer: %v", err)
	}

	pm.status = "stopped"
	pm.cmd = nil
	return nil
}

// GetStatus returns the last known state of the pool manager, for use by
// performLocalChecks alongside patroni/backup status.
func (pm *PoolManager) GetStatus() string {
	pm.mu.Lock()
	defer pm.mu.Unlock()
	return pm.status
}

// DroppedStatsCount reports how many stats samples were dropped because the
// shipping sink couldn't keep up. Non-zero is not an outage — it's proof
// the system degrades gracefully under logging backpressure instead of
// blocking client connections (this is what "decoupled" actually means).
func (pm *PoolManager) DroppedStatsCount() int64 {
	pm.mu.Lock()
	defer pm.mu.Unlock()
	return pm.droppedStats
}

// --- Phase 1.2: decoupled async stats pipeline ---
//
// Two goroutines, connected by a buffered channel:
//   1. poller: queries pgbouncer's admin console on an interval, pushes
//      raw stat lines onto statsCh. Never touches disk/network directly.
//   2. shipper: drains statsCh, writes to StatsLogPath. If this goroutine
//      stalls (slow disk, full disk, whatever), the channel buffer absorbs
//      it up to StatsBufferSize. Beyond that, samples are dropped and
//      droppedStats increments — the poller and any client connection to
//      the primary are never blocked by a slow sink.

func (pm *PoolManager) startStatsPipeline() {
	pm.statsCh = make(chan string, pm.Config.StatsBufferSize)
	pm.statsDone = make(chan struct{})

	pm.statsWG.Add(2)
	go pm.statsPoller()
	go pm.statsShipper()
}

func (pm *PoolManager) stopStatsPipeline() {
	if pm.statsDone == nil {
		return
	}
	close(pm.statsDone)
	pm.statsWG.Wait()
	pm.statsDone = nil
}

func (pm *PoolManager) statsPoller() {
	defer pm.statsWG.Done()
	ticker := time.NewTicker(pm.Config.StatsPollInterval)
	defer ticker.Stop()

	for {
		select {
		case <-pm.statsDone:
			close(pm.statsCh)
			return
		case <-ticker.C:
			line, err := pm.queryAdminStats()
			if err != nil {
				log.Printf("pool: stats poll failed: %v", err)
				continue
			}
			select {
			case pm.statsCh <- line:
			default:
				// Buffer full — drop this sample rather than block.
				// This is the actual mechanism behind "zero connection
				// exhaustion": a slow sink can never back up into a
				// blocked poller or a blocked client connection.
				pm.mu.Lock()
				pm.droppedStats++
				pm.mu.Unlock()
			}
		}
	}
}

func (pm *PoolManager) statsShipper() {
	defer pm.statsWG.Done()

	f, err := os.OpenFile(pm.Config.StatsLogPath, os.O_APPEND|os.O_CREATE|os.O_WRONLY, 0644)
	if err != nil {
		log.Printf("pool: cannot open stats log %s: %v (stats will be dropped)", pm.Config.StatsLogPath, err)
		// Drain the channel so the poller never blocks, even with no sink.
		for range pm.statsCh {
			pm.mu.Lock()
			pm.droppedStats++
			pm.mu.Unlock()
		}
		return
	}
	defer f.Close()
	w := bufio.NewWriter(f)
	defer w.Flush()

	for line := range pm.statsCh {
		if _, err := w.WriteString(line + "\n"); err != nil {
			log.Printf("pool: stats write failed: %v", err)
			continue
		}
		// Flush after every sample rather than only at shutdown. This is a
		// telemetry stream, not a bulk log — a reader checking the file
		// mid-run (an operator, a dashboard, this test harness) should see
		// data as it arrives, not just whatever was buffered when the
		// pipeline eventually stops.
		if err := w.Flush(); err != nil {
			log.Printf("pool: stats flush failed: %v", err)
		}
	}
}

// queryAdminStats connects to pgbouncer's admin console and pulls SHOW STATS.
// This talks to pgbouncer's own admin database, never the primary Postgres
// connections client traffic uses — that separation is what keeps this
// out-of-band.
func (pm *PoolManager) queryAdminStats() (string, error) {
	if pm.Config.AdminDSN == "" {
		return "", fmt.Errorf("AdminDSN not configured")
	}
	db, err := sql.Open("postgres", pm.Config.AdminDSN)
	if err != nil {
		return "", err
	}
	defer db.Close()

	rows, err := db.Query("SHOW STATS")
	if err != nil {
		return "", fmt.Errorf("SHOW STATS query failed: %w", err)
	}
	defer rows.Close()

	cols, err := rows.Columns()
	if err != nil {
		return "", fmt.Errorf("SHOW STATS columns failed: %w", err)
	}

	// SHOW STATS returns one row per database, with a variable number of
	// columns depending on pgbouncer version. Scan generically instead of
	// assuming a fixed column count, and format every row we get back.
	var out []string
	for rows.Next() {
		vals := make([]sql.RawBytes, len(cols))
		scanDest := make([]interface{}, len(cols))
		for i := range vals {
			scanDest[i] = &vals[i]
		}
		if err := rows.Scan(scanDest...); err != nil {
			return "", fmt.Errorf("SHOW STATS row scan failed: %w", err)
		}
		parts := make([]string, len(cols))
		for i, v := range vals {
			parts[i] = cols[i] + "=" + string(v)
		}
		out = append(out, "{"+fmt.Sprintf("%v", parts)+"}")
	}
	if err := rows.Err(); err != nil {
		return "", fmt.Errorf("SHOW STATS row iteration failed: %w", err)
	}

	return fmt.Sprintf("%d %v", time.Now().Unix(), out), nil
}

// GenerateUserlist writes pgbouncer's userlist.txt (auth file) if it does
// not already exist. Mirrors GenerateIni's "skip if exists" behavior so
// re-running InitPool never clobbers a userlist that's already in place.
func (pm *PoolManager) GenerateUserlist() error {
 if pm.Config.AuthFile == "" {
  return fmt.Errorf("AuthFile is empty, cannot generate userlist.txt")
 }
 if pm.Config.PgUser == "" || pm.Config.PgPassword == "" {
  return fmt.Errorf("PgUser/PgPassword not set, cannot generate userlist.txt")
 }

 if _, err := os.Stat(pm.Config.AuthFile); err == nil {
  return nil
 }

 dir := filepath.Dir(pm.Config.AuthFile)
 if err := os.MkdirAll(dir, 0755); err != nil {
  return fmt.Errorf("failed to create directory for userlist.txt: %w", err)
 }

 hash := md5.Sum([]byte(pm.Config.PgPassword + pm.Config.PgUser))
	md5Hash := "md5" + hex.EncodeToString(hash[:])
	userlist := fmt.Sprintf("%q %q\n", pm.Config.PgUser, md5Hash)
 if err := os.WriteFile(pm.Config.AuthFile, []byte(userlist), 0600); err != nil {
  return fmt.Errorf("failed to write userlist.txt: %w", err)
 }

 return nil
}
